### ISSUE TITLE
Support HHVM

### ISSUE THREAD

**Issue by mazurva** [dmstr/yii2-migrate-command#11]
Maybe it's just a bug Travis CI:

```
Lookup:
    @app/migrations (/home/travis/build/sibds/yii2-enterprise/console/migrations)
Fatal error: Uncaught exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @bedezign/yii2/audit/migrations' in /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/BaseYii.php:152
Stack trace:
#0 /home/travis/build/sibds/yii2-enterprise/vendor/dmstr/yii2-migrate-command/MigrateController.php(757): yii\BaseYii::getAlias()
#1 /home/travis/build/sibds/yii2-enterprise/vendor/dmstr/yii2-migrate-command/MigrateController.php(174): dmstr\console\controllers\MigrateController->getNewMigrations()
#2 (): dmstr\console\controllers\MigrateController->actionUp()
#3 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array()
#4 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams()
#5 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction()
#6 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction()
#7 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Application.php(166): yii\base\Module->runAction()
#8 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Application.php(142): yii\console\Application->runAction()
#9 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#10 /home/travis/build/sibds/yii2-enterprise/tests/codeception/bin/yii(22): yii\base\Application->run()
#11 {main}
An Error occurred while handling another error:
exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Response::isSent' in /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Component.php:197
Stack trace:
#0 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/web/ErrorHandler.php(74): yii\base\Component->__set()
#1 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/ErrorHandler.php(109): yii\web\ErrorHandler->renderException()
#2 (): yii\base\ErrorHandler->handleException()
#3 {main}
Previous exception:
exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @bedezign/yii2/audit/migrations' in /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/BaseYii.php:152
Stack trace:
#0 /home/travis/build/sibds/yii2-enterprise/vendor/dmstr/yii2-migrate-command/MigrateController.php(757): yii\BaseYii::getAlias()
#1 /home/travis/build/sibds/yii2-enterprise/vendor/dmstr/yii2-migrate-command/MigrateController.php(174): dmstr\console\controllers\MigrateController->getNewMigrations()
#2 (): dmstr\console\controllers\MigrateController->actionUp()
#3 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array()
#4 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams()
#5 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction()
#6 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction()
#7 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Application.php(166): yii\base\Module->runAction()
#8 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/console/Application.php(142): yii\console\Application->runAction()
#9 /home/travis/build/sibds/yii2-enterprise/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest()
#10 /home/travis/build/sibds/yii2-enterprise/tests/codeception/bin/yii(22): yii\base\Application->run()
#11 {main}
```

**Comment by schmunk42** [comment]
Closing, since this extension is no longer actively developed.
